---
kind: pipeline
type: docker
name: testing

platform:
  os: linux
  arch: amd64

steps:
- name: prepare
  image: webhippie/nodejs:latest
  pull: always
  commands:
  - yarn install --frozen-lockfile

- name: lint
  image: webhippie/nodejs:latest
  pull: always
  commands:
  - yarn lint

- name: build
  image: webhippie/nodejs:latest
  pull: always
  commands:
  - yarn build

- name: publish
  image: lucap/drone-netlify:latest
  pull: always
  settings:
    token:
      from_secret: netlify_token
    site_id: d523079f-b914-438b-b6da-f3c3eeae6d49
    path: dist/
  when:
    event:
      exclude:
      - pull_request

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

...
